using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;
using Transport.Data.Models;

namespace Transport.Data
{
    public class TransportDbContext : DbContext
    {
        public DbSet<BusStop> BusStops { get; set; }
        public DbSet<BusLine> BusLines { get; set; }
        public DbSet<RouteStop> RouteStops { get; set; }
        public DbSet<Schedule> Schedules { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=TransportSystem.db");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BusStop>().Property(s => s.Name).IsRequired().HasMaxLength(100);
            modelBuilder.Entity<BusLine>().Property(l => l.Number).IsRequired();

            modelBuilder.Entity<BusStop>().HasData(
                new BusStop { Id = 1, Name = "Терминал Изгрев" },
                new BusStop { Id = 2, Name = "Акве Калиде" },
                new BusStop { Id = 3, Name = "Добри Чинтулов" },
                new BusStop { Id = 4, Name = "Велека" },
                new BusStop { Id = 5, Name = "Никола Петков" },
                new BusStop { Id = 6, Name = "Зорница" },
                new BusStop { Id = 7, Name = "Стефан Стамболов" },
                new BusStop { Id = 8, Name = "Александровска" },
                new BusStop { Id = 9, Name = "Опера" },
                new BusStop { Id = 10, Name = "Терминал Юг" },
                new BusStop { Id = 11, Name = "Спортна" },
                new BusStop { Id = 12, Name = "Езеро Вая" },
                new BusStop { Id = 13, Name = "Захари Стоянов" },
                new BusStop { Id = 14, Name = "Резвая" },
                new BusStop { Id = 15, Name = "Бадемите" },
                new BusStop { Id = 16, Name = "Терминал М. Рудник" },
                new BusStop { Id = 17, Name = "Терминал Славейков" },
                new BusStop { Id = 18, Name = "Янко Комитов" },
                new BusStop { Id = 19, Name = "А. Страшимиров" },
                new BusStop { Id = 20, Name = "Тракия" },
                new BusStop { Id = 21, Name = "Младост" },
                new BusStop { Id = 22, Name = "Ст. Стамболов" },
                new BusStop { Id = 23, Name = "Т. М. Рудник" },
                new BusStop { Id = 24, Name = "Славейков, бл. 35" },
                new BusStop { Id = 25, Name = "Славейков, бл. 37" },
                new BusStop { Id = 26, Name = "У-тет Проф. Ас. Златаров" },
                new BusStop { Id = 27, Name = "Транспортна" },
                new BusStop { Id = 28, Name = "Изгрев, бл. 40" },
                new BusStop { Id = 29, Name = "Парк Езеро" },
                new BusStop { Id = 30, Name = "Стадион Лазур" },
                new BusStop { Id = 31, Name = "Копривщица" },
                new BusStop { Id = 32, Name = "К. Величков" },
                new BusStop { Id = 33, Name = "Сан Стефано" },
                new BusStop { Id = 34, Name = "Ген. Гурко" },
                new BusStop { Id = 35, Name = "Булаир" },
                new BusStop { Id = 36, Name = "Транспортна болница" },
                new BusStop { Id = 37, Name = "Иван Вазов" },
                new BusStop { Id = 38, Name = "Сливница" },
                new BusStop { Id = 39, Name = "Мария Луиза" },
                new BusStop { Id = 40, Name = "Автогара Запад" },
                new BusStop { Id = 41, Name = "Одрин" },
                new BusStop { Id = 42, Name = "Трапезица" },
                new BusStop { Id = 43, Name = "Струга" },
                new BusStop { Id = 44, Name = "Славейков, бл. 1" },
                new BusStop { Id = 45, Name = "Лазар Маджаров" },
                new BusStop { Id = 46, Name = "Славейков, бл. 9" },
                new BusStop { Id = 47, Name = "Славейков, бл. 16" },
                new BusStop { Id = 48, Name = "Славейков, бл. 30" },
                new BusStop { Id = 49, Name = "Славейков, бл. 31" },
                new BusStop { Id = 50, Name = "24-ти пехотен полк" },
                new BusStop { Id = 51, Name = "Изгрев, бл. 39" },
                new BusStop { Id = 52, Name = "МБАЛ Сърце и мозък" },
                new BusStop { Id = 53, Name = "Автогара Юг" },
                new BusStop { Id = 54, Name = "Дунав" },
                new BusStop { Id = 55, Name = "Демокрация" },
                new BusStop { Id = 56, Name = "Изгрев, бл. 3" },
                new BusStop { Id = 57, Name = "Гробищен парк" },
                new BusStop { Id = 58, Name = "Летище Бургас" },
                new BusStop { Id = 59, Name = "Сарафово, Октомври" },
                new BusStop { Id = 60, Name = "Сарафово, Драва" },
                new BusStop { Id = 61, Name = "Сарафово, Брацигово" },
                new BusStop { Id = 62, Name = "Сарафово, Ради Николов" },
                new BusStop { Id = 63, Name = "Сарафово, Лазурна" },
                new BusStop { Id = 64, Name = "Сарафово, А. Димитров" },
                new BusStop { Id = 65, Name = "Антон Страшимиров" },
                new BusStop { Id = 66, Name = "Капчето" },
                new BusStop { Id = 67, Name = "Тополица" },
                new BusStop { Id = 68, Name = "Въстаническа" },
                new BusStop { Id = 69, Name = "Найден Геров" },
                new BusStop { Id = 70, Name = "М. рудник, бл. 485" },
                new BusStop { Id = 71, Name = "М. рудник, бл. 101" },
                new BusStop { Id = 72, Name = "Терминал М. рудник" }
                );
            modelBuilder.Entity<BusLine>().HasData(
                new BusLine { Id = 1, Number = "Б1" },
                new BusLine { Id = 2, Number = "Б2" },
                new BusLine { Id = 3, Number = "Б11" },
                new BusLine { Id = 4, Number = "Б12" },
                new BusLine { Id = 5, Number = "11" },
                new BusLine { Id = 6, Number = "12" },
                new BusLine { Id = 7, Number = "15" },
                new BusLine { Id = 8, Number = "Нощна Линия" }
                );
            modelBuilder.Entity<RouteStop>().HasData(
                //Линия Б1 (Id = 1)
                new RouteStop { Id = 1, BusLineId = 1, BusStopId = 1, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 2, BusLineId = 1, BusStopId = 2, StopOrder = 2, MinutesFromStart = 2 },
                new RouteStop { Id = 3, BusLineId = 1, BusStopId = 3, StopOrder = 3, MinutesFromStart = 3 },
                new RouteStop { Id = 4, BusLineId = 1, BusStopId = 4, StopOrder = 4, MinutesFromStart = 5 },
                new RouteStop { Id = 5, BusLineId = 1, BusStopId = 5, StopOrder = 5, MinutesFromStart = 7 },
                new RouteStop { Id = 6, BusLineId = 1, BusStopId = 6, StopOrder = 6, MinutesFromStart = 9 },
                new RouteStop { Id = 7, BusLineId = 1, BusStopId = 7, StopOrder = 7, MinutesFromStart = 11 },
                new RouteStop { Id = 8, BusLineId = 1, BusStopId = 8, StopOrder = 8, MinutesFromStart = 13 },
                new RouteStop { Id = 9, BusLineId = 1, BusStopId = 9, StopOrder = 9, MinutesFromStart = 15 },
                new RouteStop { Id = 10, BusLineId = 1, BusStopId = 10, StopOrder = 10, MinutesFromStart = 17 },
                new RouteStop { Id = 11, BusLineId = 1, BusStopId = 11, StopOrder = 11, MinutesFromStart = 20 },
                new RouteStop { Id = 12, BusLineId = 1, BusStopId = 12, StopOrder = 12, MinutesFromStart = 24 },
                new RouteStop { Id = 13, BusLineId = 1, BusStopId = 13, StopOrder = 13, MinutesFromStart = 27 },
                new RouteStop { Id = 14, BusLineId = 1, BusStopId = 14, StopOrder = 14, MinutesFromStart = 29 },
                new RouteStop { Id = 15, BusLineId = 1, BusStopId = 15, StopOrder = 15, MinutesFromStart = 31 },
                new RouteStop { Id = 16, BusLineId = 1, BusStopId = 16, StopOrder = 16, MinutesFromStart = 34 },

                //Линия Б2 (Id = 2)
                new RouteStop { Id = 17, BusLineId = 2, BusStopId = 17, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 18, BusLineId = 2, BusStopId = 18, StopOrder = 2, MinutesFromStart = 2 },
                new RouteStop { Id = 19, BusLineId = 2, BusStopId = 19, StopOrder = 3, MinutesFromStart = 3 },
                new RouteStop { Id = 20, BusLineId = 2, BusStopId = 20, StopOrder = 4, MinutesFromStart = 5 },
                new RouteStop { Id = 21, BusLineId = 2, BusStopId = 21, StopOrder = 5, MinutesFromStart = 7 },
                new RouteStop { Id = 22, BusLineId = 2, BusStopId = 6, StopOrder = 6, MinutesFromStart = 9 },
                new RouteStop { Id = 23, BusLineId = 2, BusStopId = 22, StopOrder = 7, MinutesFromStart = 12 },
                new RouteStop { Id = 24, BusLineId = 2, BusStopId = 8, StopOrder = 8, MinutesFromStart = 14 },
                new RouteStop { Id = 25, BusLineId = 2, BusStopId = 9, StopOrder = 9, MinutesFromStart = 16 },
                new RouteStop { Id = 26, BusLineId = 2, BusStopId = 10, StopOrder = 10, MinutesFromStart = 18 },
                new RouteStop { Id = 27, BusLineId = 2, BusStopId = 11, StopOrder = 11, MinutesFromStart = 21 },
                new RouteStop { Id = 28, BusLineId = 2, BusStopId = 12, StopOrder = 12, MinutesFromStart = 25 },
                new RouteStop { Id = 29, BusLineId = 2, BusStopId = 13, StopOrder = 13, MinutesFromStart = 28 },
                new RouteStop { Id = 30, BusLineId = 2, BusStopId = 14, StopOrder = 14, MinutesFromStart = 30 },
                new RouteStop { Id = 31, BusLineId = 2, BusStopId = 15, StopOrder = 15, MinutesFromStart = 32 },
                new RouteStop { Id = 32, BusLineId = 2, BusStopId = 23, StopOrder = 16, MinutesFromStart = 35 },

                //ЛинияБ11 (Id = 3)
                new RouteStop { Id = 200, BusLineId = 3, BusStopId = 1, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 201, BusLineId = 3, BusStopId = 100, StopOrder = 2, MinutesFromStart = 2 },
                new RouteStop { Id = 202, BusLineId = 3, BusStopId = 101, StopOrder = 3, MinutesFromStart = 3 },
                new RouteStop { Id = 203, BusLineId = 3, BusStopId = 5, StopOrder = 4, MinutesFromStart = 5 },
                new RouteStop { Id = 204, BusLineId = 3, BusStopId = 102, StopOrder = 5, MinutesFromStart = 7 },
                new RouteStop { Id = 205, BusLineId = 3, BusStopId = 6, StopOrder = 6, MinutesFromStart = 8 },
                new RouteStop { Id = 206, BusLineId = 3, BusStopId = 55, StopOrder = 7, MinutesFromStart = 10 },
                new RouteStop { Id = 207, BusLineId = 3, BusStopId = 54, StopOrder = 8, MinutesFromStart = 12 },
                new RouteStop { Id = 208, BusLineId = 3, BusStopId = 33, StopOrder = 9, MinutesFromStart = 14 },
                new RouteStop { Id = 209, BusLineId = 3, BusStopId = 34, StopOrder = 10, MinutesFromStart = 16 },
                new RouteStop { Id = 210, BusLineId = 3, BusStopId = 35, StopOrder = 11, MinutesFromStart = 18 },
                new RouteStop { Id = 211, BusLineId = 3, BusStopId = 36, StopOrder = 12, MinutesFromStart = 19 },
                new RouteStop { Id = 212, BusLineId = 3, BusStopId = 37, StopOrder = 13, MinutesFromStart = 21 },
                new RouteStop { Id = 213, BusLineId = 3, BusStopId = 11, StopOrder = 14, MinutesFromStart = 23 },
                new RouteStop { Id = 214, BusLineId = 3, BusStopId = 12, StopOrder = 15, MinutesFromStart = 27 },
                new RouteStop { Id = 215, BusLineId = 3, BusStopId = 66, StopOrder = 16, MinutesFromStart = 30 },
                new RouteStop { Id = 216, BusLineId = 3, BusStopId = 67, StopOrder = 17, MinutesFromStart = 33 },
                new RouteStop { Id = 217, BusLineId = 3, BusStopId = 13, StopOrder = 18, MinutesFromStart = 36 },
                new RouteStop { Id = 218, BusLineId = 3, BusStopId = 68, StopOrder = 19, MinutesFromStart = 38 },
                new RouteStop { Id = 219, BusLineId = 3, BusStopId = 14, StopOrder = 20, MinutesFromStart = 40 },
                new RouteStop { Id = 220, BusLineId = 3, BusStopId = 69, StopOrder = 21, MinutesFromStart = 42 },
                new RouteStop { Id = 221, BusLineId = 3, BusStopId = 70, StopOrder = 22, MinutesFromStart = 44 },
                new RouteStop { Id = 222, BusLineId = 3, BusStopId = 71, StopOrder = 23, MinutesFromStart = 46 },
                new RouteStop { Id = 223, BusLineId = 3, BusStopId = 15, StopOrder = 24, MinutesFromStart = 48 },
                new RouteStop { Id = 224, BusLineId = 3, BusStopId = 72, StopOrder = 25, MinutesFromStart = 50 },

                //Линия Б12 (Id = 4)
                new RouteStop { Id = 400, BusLineId = 4, BusStopId = 17, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 401, BusLineId = 4, BusStopId = 24, StopOrder = 2, MinutesFromStart = 2 },
                new RouteStop { Id = 402, BusLineId = 4, BusStopId = 25, StopOrder = 3, MinutesFromStart = 3 },
                new RouteStop { Id = 403, BusLineId = 4, BusStopId = 26, StopOrder = 4, MinutesFromStart = 5 },
                new RouteStop { Id = 404, BusLineId = 4, BusStopId = 20, StopOrder = 5, MinutesFromStart = 7 },
                new RouteStop { Id = 405, BusLineId = 4, BusStopId = 21, StopOrder = 6, MinutesFromStart = 9 },
                new RouteStop { Id = 406, BusLineId = 4, BusStopId = 6, StopOrder = 7, MinutesFromStart = 11 },
                new RouteStop { Id = 407, BusLineId = 4, BusStopId = 55, StopOrder = 8, MinutesFromStart = 13 },
                new RouteStop { Id = 408, BusLineId = 4, BusStopId = 54, StopOrder = 9, MinutesFromStart = 15 },
                new RouteStop { Id = 409, BusLineId = 4, BusStopId = 33, StopOrder = 10, MinutesFromStart = 17 },
                new RouteStop { Id = 410, BusLineId = 4, BusStopId = 34, StopOrder = 11, MinutesFromStart = 19 },
                new RouteStop { Id = 411, BusLineId = 4, BusStopId = 35, StopOrder = 12, MinutesFromStart = 21 },
                new RouteStop { Id = 412, BusLineId = 4, BusStopId = 36, StopOrder = 13, MinutesFromStart = 22 },
                new RouteStop { Id = 413, BusLineId = 4, BusStopId = 37, StopOrder = 14, MinutesFromStart = 24 },
                new RouteStop { Id = 414, BusLineId = 4, BusStopId = 11, StopOrder = 15, MinutesFromStart = 26 },
                new RouteStop { Id = 415, BusLineId = 4, BusStopId = 12, StopOrder = 16, MinutesFromStart = 30 },
                new RouteStop { Id = 416, BusLineId = 4, BusStopId = 66, StopOrder = 17, MinutesFromStart = 33 },
                new RouteStop { Id = 417, BusLineId = 4, BusStopId = 67, StopOrder = 18, MinutesFromStart = 36 },
                new RouteStop { Id = 418, BusLineId = 4, BusStopId = 13, StopOrder = 19, MinutesFromStart = 39 },
                new RouteStop { Id = 419, BusLineId = 4, BusStopId = 68, StopOrder = 20, MinutesFromStart = 41 },
                new RouteStop { Id = 420, BusLineId = 4, BusStopId = 14, StopOrder = 21, MinutesFromStart = 43 },
                new RouteStop { Id = 421, BusLineId = 4, BusStopId = 69, StopOrder = 22, MinutesFromStart = 45 },
                new RouteStop { Id = 422, BusLineId = 4, BusStopId = 70, StopOrder = 23, MinutesFromStart = 47 },
                new RouteStop { Id = 423, BusLineId = 4, BusStopId = 71, StopOrder = 24, MinutesFromStart = 49 },
                new RouteStop { Id = 424, BusLineId = 4, BusStopId = 15, StopOrder = 25, MinutesFromStart = 51 },
                new RouteStop { Id = 425, BusLineId = 4, BusStopId = 72, StopOrder = 26, MinutesFromStart = 53 },
                
                //Линия11 (Id = 5)
                new RouteStop { Id = 500, BusLineId = 5, BusStopId = 17, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 501, BusLineId = 5, BusStopId = 24, StopOrder = 2, MinutesFromStart = 1 },
                new RouteStop { Id = 502, BusLineId = 5, BusStopId = 25, StopOrder = 3, MinutesFromStart = 2 },
                new RouteStop { Id = 503, BusLineId = 5, BusStopId = 26, StopOrder = 4, MinutesFromStart = 4 },
                new RouteStop { Id = 504, BusLineId = 5, BusStopId = 27, StopOrder = 5, MinutesFromStart = 6 },
                new RouteStop { Id = 505, BusLineId = 5, BusStopId = 2, StopOrder = 6, MinutesFromStart = 8 },
                new RouteStop { Id = 506, BusLineId = 5, BusStopId = 3, StopOrder = 7, MinutesFromStart = 9 },
                new RouteStop { Id = 507, BusLineId = 5, BusStopId = 28, StopOrder = 8, MinutesFromStart = 11 },
                new RouteStop { Id = 508, BusLineId = 5, BusStopId = 5, StopOrder = 9, MinutesFromStart = 13 },
                new RouteStop { Id = 509, BusLineId = 5, BusStopId = 29, StopOrder = 10, MinutesFromStart = 15 },
                new RouteStop { Id = 510, BusLineId = 5, BusStopId = 30, StopOrder = 11, MinutesFromStart = 17 },
                new RouteStop { Id = 511, BusLineId = 5, BusStopId = 31, StopOrder = 12, MinutesFromStart = 18 },
                new RouteStop { Id = 512, BusLineId = 5, BusStopId = 32, StopOrder = 13, MinutesFromStart = 20 },
                new RouteStop { Id = 513, BusLineId = 5, BusStopId = 33, StopOrder = 14, MinutesFromStart = 22 },
                new RouteStop { Id = 514, BusLineId = 5, BusStopId = 34, StopOrder = 15, MinutesFromStart = 24 },
                new RouteStop { Id = 515, BusLineId = 5, BusStopId = 35, StopOrder = 16, MinutesFromStart = 26 },
                new RouteStop { Id = 516, BusLineId = 5, BusStopId = 10, StopOrder = 17, MinutesFromStart = 28 },
                new RouteStop { Id = 517, BusLineId = 5, BusStopId = 36, StopOrder = 18, MinutesFromStart = 29 },
                new RouteStop { Id = 518, BusLineId = 5, BusStopId = 37, StopOrder = 19, MinutesFromStart = 31 },
                new RouteStop { Id = 519, BusLineId = 5, BusStopId = 38, StopOrder = 20, MinutesFromStart = 33 },
                new RouteStop { Id = 520, BusLineId = 5, BusStopId = 39, StopOrder = 21, MinutesFromStart = 35 },
                new RouteStop { Id = 521, BusLineId = 5, BusStopId = 40, StopOrder = 22, MinutesFromStart = 38 },
                new RouteStop { Id = 522, BusLineId = 5, BusStopId = 41, StopOrder = 23, MinutesFromStart = 40 },
                new RouteStop { Id = 523, BusLineId = 5, BusStopId = 42, StopOrder = 24, MinutesFromStart = 42 },
                new RouteStop { Id = 524, BusLineId = 5, BusStopId = 43, StopOrder = 25, MinutesFromStart = 44 },
                new RouteStop { Id = 525, BusLineId = 5, BusStopId = 6, StopOrder = 26, MinutesFromStart = 46 },
                new RouteStop { Id = 526, BusLineId = 5, BusStopId = 44, StopOrder = 27, MinutesFromStart = 49 },
                new RouteStop { Id = 527, BusLineId = 5, BusStopId = 45, StopOrder = 28, MinutesFromStart = 51 },
                new RouteStop { Id = 528, BusLineId = 5, BusStopId = 46, StopOrder = 29, MinutesFromStart = 53 },
                new RouteStop { Id = 529, BusLineId = 5, BusStopId = 47, StopOrder = 30, MinutesFromStart = 54 },
                new RouteStop { Id = 530, BusLineId = 5, BusStopId = 48, StopOrder = 31, MinutesFromStart = 56 },
                new RouteStop { Id = 531, BusLineId = 5, BusStopId = 18, StopOrder = 32, MinutesFromStart = 58 },
                new RouteStop { Id = 532, BusLineId = 5, BusStopId = 17, StopOrder = 33, MinutesFromStart = 60 },

                //Линия 12 (Id = 6)
                new RouteStop { Id = 600, BusLineId = 6, BusStopId = 17, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 601, BusLineId = 6, BusStopId = 49, StopOrder = 2, MinutesFromStart = 1 },
                new RouteStop { Id = 602, BusLineId = 6, BusStopId = 48, StopOrder = 3, MinutesFromStart = 2 },
                new RouteStop { Id = 603, BusLineId = 6, BusStopId = 47, StopOrder = 4, MinutesFromStart = 3 },
                new RouteStop { Id = 604, BusLineId = 6, BusStopId = 46, StopOrder = 5, MinutesFromStart = 4 },
                new RouteStop { Id = 605, BusLineId = 6, BusStopId = 45, StopOrder = 6, MinutesFromStart = 6 },
                new RouteStop { Id = 606, BusLineId = 6, BusStopId = 44, StopOrder = 7, MinutesFromStart = 8 },
                new RouteStop { Id = 607, BusLineId = 6, BusStopId = 6, StopOrder = 8, MinutesFromStart = 11 },
                new RouteStop { Id = 608, BusLineId = 6, BusStopId = 43, StopOrder = 9, MinutesFromStart = 13 },
                new RouteStop { Id = 609, BusLineId = 6, BusStopId = 42, StopOrder = 10, MinutesFromStart = 15 },
                new RouteStop { Id = 610, BusLineId = 6, BusStopId = 41, StopOrder = 11, MinutesFromStart = 17 },
                new RouteStop { Id = 611, BusLineId = 6, BusStopId = 40, StopOrder = 12, MinutesFromStart = 20 },
                new RouteStop { Id = 612, BusLineId = 6, BusStopId = 39, StopOrder = 13, MinutesFromStart = 22 },
                new RouteStop { Id = 613, BusLineId = 6, BusStopId = 38, StopOrder = 14, MinutesFromStart = 24 },
                new RouteStop { Id = 614, BusLineId = 6, BusStopId = 37, StopOrder = 15, MinutesFromStart = 26 },
                new RouteStop { Id = 615, BusLineId = 6, BusStopId = 10, StopOrder = 16, MinutesFromStart = 29 },
                new RouteStop { Id = 616, BusLineId = 6, BusStopId = 35, StopOrder = 17, MinutesFromStart = 31 },
                new RouteStop { Id = 617, BusLineId = 6, BusStopId = 50, StopOrder = 18, MinutesFromStart = 33 },
                new RouteStop { Id = 618, BusLineId = 6, BusStopId = 32, StopOrder = 19, MinutesFromStart = 35 },
                new RouteStop { Id = 619, BusLineId = 6, BusStopId = 31, StopOrder = 20, MinutesFromStart = 37 },
                new RouteStop { Id = 620, BusLineId = 6, BusStopId = 30, StopOrder = 21, MinutesFromStart = 39 },
                new RouteStop { Id = 621, BusLineId = 6, BusStopId = 29, StopOrder = 22, MinutesFromStart = 41 },
                new RouteStop { Id = 622, BusLineId = 6, BusStopId = 5, StopOrder = 23, MinutesFromStart = 43 },
                new RouteStop { Id = 623, BusLineId = 6, BusStopId = 51, StopOrder = 24, MinutesFromStart = 45 },
                new RouteStop { Id = 624, BusLineId = 6, BusStopId = 3, StopOrder = 25, MinutesFromStart = 47 },
                new RouteStop { Id = 625, BusLineId = 6, BusStopId = 2, StopOrder = 26, MinutesFromStart = 48 },
                new RouteStop { Id = 626, BusLineId = 6, BusStopId = 17, StopOrder = 27, MinutesFromStart = 50 },

                //Линия 15 (Id = 7)
                new RouteStop { Id = 62, BusLineId = 7, BusStopId = 53, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 63, BusLineId = 7, BusStopId = 35, StopOrder = 2, MinutesFromStart = 2 },
                new RouteStop { Id = 64, BusLineId = 7, BusStopId = 34, StopOrder = 3, MinutesFromStart = 4 },
                new RouteStop { Id = 65, BusLineId = 7, BusStopId = 33, StopOrder = 4, MinutesFromStart = 6 },
                new RouteStop { Id = 66, BusLineId = 7, BusStopId = 54, StopOrder = 5, MinutesFromStart = 8 },
                new RouteStop { Id = 67, BusLineId = 7, BusStopId = 55, StopOrder = 6, MinutesFromStart = 10 },
                new RouteStop { Id = 68, BusLineId = 7, BusStopId = 6, StopOrder = 7, MinutesFromStart = 12 },
                new RouteStop { Id = 69, BusLineId = 7, BusStopId = 21, StopOrder = 8, MinutesFromStart = 14 },
                new RouteStop { Id = 70, BusLineId = 7, BusStopId = 56, StopOrder = 9, MinutesFromStart = 16 },
                new RouteStop { Id = 71, BusLineId = 7, BusStopId = 27, StopOrder = 10, MinutesFromStart = 18 },
                new RouteStop { Id = 72, BusLineId = 7, BusStopId = 57, StopOrder = 11, MinutesFromStart = 21 },
                new RouteStop { Id = 73, BusLineId = 7, BusStopId = 58, StopOrder = 12, MinutesFromStart = 25 },
                new RouteStop { Id = 74, BusLineId = 7, BusStopId = 59, StopOrder = 13, MinutesFromStart = 28 },
                new RouteStop { Id = 75, BusLineId = 7, BusStopId = 60, StopOrder = 14, MinutesFromStart = 29 },
                new RouteStop { Id = 76, BusLineId = 7, BusStopId = 61, StopOrder = 15, MinutesFromStart = 30 },
                new RouteStop { Id = 77, BusLineId = 7, BusStopId = 62, StopOrder = 16, MinutesFromStart = 31 },
                new RouteStop { Id = 78, BusLineId = 7, BusStopId = 63, StopOrder = 17, MinutesFromStart = 32 },
                new RouteStop { Id = 79, BusLineId = 7, BusStopId = 64, StopOrder = 18, MinutesFromStart = 35 },

                //Нощна Линия(Id = 8)
                new RouteStop { Id = 800, BusLineId = 8, BusStopId = 17, StopOrder = 1, MinutesFromStart = 0 },
                new RouteStop { Id = 801, BusLineId = 8, BusStopId = 49, StopOrder = 2, MinutesFromStart = 1 },
                new RouteStop { Id = 802, BusLineId = 8, BusStopId = 18, StopOrder = 3, MinutesFromStart = 2 },
                new RouteStop { Id = 803, BusLineId = 8, BusStopId = 65, StopOrder = 4, MinutesFromStart = 3 },
                new RouteStop { Id = 804, BusLineId = 8, BusStopId = 20, StopOrder = 5, MinutesFromStart = 5 },
                new RouteStop { Id = 805, BusLineId = 8, BusStopId = 21, StopOrder = 6, MinutesFromStart = 7 },
                new RouteStop { Id = 806, BusLineId = 8, BusStopId = 6, StopOrder = 7, MinutesFromStart = 9 },
                new RouteStop { Id = 807, BusLineId = 8, BusStopId = 7, StopOrder = 8, MinutesFromStart = 11 },
                new RouteStop { Id = 808, BusLineId = 8, BusStopId = 8, StopOrder = 9, MinutesFromStart = 13 },
                new RouteStop { Id = 809, BusLineId = 8, BusStopId = 9, StopOrder = 10, MinutesFromStart = 15 },
                new RouteStop { Id = 810, BusLineId = 8, BusStopId = 10, StopOrder = 11, MinutesFromStart = 17 },
                new RouteStop { Id = 811, BusLineId = 8, BusStopId = 36, StopOrder = 12, MinutesFromStart = 18 },
                new RouteStop { Id = 812, BusLineId = 8, BusStopId = 37, StopOrder = 13, MinutesFromStart = 20 },
                new RouteStop { Id = 813, BusLineId = 8, BusStopId = 11, StopOrder = 14, MinutesFromStart = 22 },
                new RouteStop { Id = 814, BusLineId = 8, BusStopId = 12, StopOrder = 15, MinutesFromStart = 25 },
                new RouteStop { Id = 815, BusLineId = 8, BusStopId = 66, StopOrder = 16, MinutesFromStart = 27 },
                new RouteStop { Id = 816, BusLineId = 8, BusStopId = 13, StopOrder = 17, MinutesFromStart = 30 },
                new RouteStop { Id = 817, BusLineId = 8, BusStopId = 67, StopOrder = 18, MinutesFromStart = 32 },
                new RouteStop { Id = 818, BusLineId = 8, BusStopId = 68, StopOrder = 19, MinutesFromStart = 34 },
                new RouteStop { Id = 819, BusLineId = 8, BusStopId = 69, StopOrder = 20, MinutesFromStart = 36 },
                new RouteStop { Id = 820, BusLineId = 8, BusStopId = 70, StopOrder = 21, MinutesFromStart = 38 },
                new RouteStop { Id = 821, BusLineId = 8, BusStopId = 71, StopOrder = 22, MinutesFromStart = 40 },
                new RouteStop { Id = 822, BusLineId = 8, BusStopId = 72, StopOrder = 23, MinutesFromStart = 43 }
                );
        }
    }
}
